language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
  - "pypy3"

install:
- pip install codecov

script:
  - python setup.py test # or py.test for Python versions 3.5 and below

after_success:
- codecov